from django.urls import path
from . import views

urlpatterns = [

    path('add/', views.add, name='Insert'),
    path('nextuser/', views.nextuser, name='nextuser'),
    path('nextuser/addnew/', views.addnew, name='Add more members'),
    path('nextuser/addnew/saveaddnew/', views.saveaddnew, name='save more members'),
    path('dd/nextuser/addnew/saveaddnew/back/', views.add, name='back page'),
    path('remaining/addmore/', views.saveaddnew),
    path('/', views.fetch),
    path('remaining/', views.addnew),
    path('', views.mainpage),
    path('teacher/', views.teacher, name='Teachers module'),
    path('ss/', views.ss, name='Authentication module'),
    path('ss/docs/', views.docs, name='Authentication module'),
    path('ss/nn/docs/', views.docs),
    path('ss/nn/groupDetails/', views.grp, name='Group Details of Teacher'),
    path('ss/groupDetails/', views.grp, name='Group Details of Teacher'),
    path('ss/Allocate/', views.grp, name='Group Details of Teacher'),
    path('ss/groupDetails/op/', views.nextgrp, name='Group Details of Teacher'),
    path('ss/groupDetails/op/', views.nextgrp, name='Group Details of Teacher'),
    path('ss/Allocate/', views.allocate, name='Allocate groups of teacher'),
    path('ss/Allocate/group/', views.marks2, name='details'),
    path('ss/Allocate/op/', views.marks2, name='details'),
    path('ss/Allocate/group/savecheckvalue/', views.check, name='details'),
    path('logged/logged/', views.loggedin),
    path('logged/logged/logged/', views.loggedin),
    path('logged/logged/logged/logged/', views.loggedin),
    path('logged/logged/logged/logged/logged/', views.loggedin),
    path('logged/logged/logged/logged/logged/logged/', views.loggedin),
    path('logged/logged/logged/logged/logged/logged/logged/', views.loggedin),
    path('next/table/', views.table),
    path('next/table/update/', views.updatetable),
    path('next/table/delete/', views.deletetable),
    path('cc/', views.submodule),
    path('ss/tracker/', views.tracking, name='Teacher project tracking'),
    path('ss/nn/tracker/', views.tracking, name='Teacher project tracking'),
    path('u/', views.loguser, name="user login"),
    path('logged/', views.loggedin, name='logged in'),
    path('nextteacher/', views.saveteacher),
    path('reg.html', views.add),
    path('userloginpage.html', views.loguser),
    path('guidelogin.html', views.tlogin),
    path('guidereg.html', views.treg),
    path('ss/', views.ss),
    path('forgot1/', views.forgot1),
    path('forgot2/', views.forgot2),
    path('forgot1/veri1/', views.verify1),
    path('forgot2/veri1/', views.verify2),
    path('forgot1/veri1/try/', views.verifailed),
    path('forgot1/veri1/newpass1/', views.newpass1),
    path('forgot2/veri1/newpass1/', views.newpass1),
    path('forgot1/veri1/newpass1/login/', views.login1),
    path('forgot2/veri1/newpass1/login/', views.login2),
    path('#', views.grp, name='Group Details of Teacher'),
    path('adminlogin.html/', views.adminlogin),
    path('adminlogin.html/adminlog/', views.adminlogged),
    path('adminlogin.html/adminlog/adminlog/', views.adminlogged),
    path('adminlogin.html/adminlog/adminlog/adminlog/', views.adminlogged),
    path('adminlogin.html/adminlog/adminlog/adminlog/adminlog/', views.adminlogged),
    path('adminlogin.html/adminlog/adminlog/adminlog/adminlog/adminlog/', views.adminlogged),
    path('adminlogin.html/adminlog/adminlog/adminlog/adminlog/adminlog/adminlog/', views.adminlogged),
    path('adminlogin.html/adminlog/adminlog/adminlog/adminlog/adminlog/adminlog/adminlog/', views.adminlogged),
    path('adminlogin.html/adminlog/manage/', views.manageresources),
    path('adminlogin.html/adminlog/manage/newadd/', views.addr),
    path('adminlogin.html/adminlog/manage/newadd/low/', views.low),
    path('adminlogin.html/adminlog/manage/low/', views.low),
    path('adminlogin.html/adminlog/manage/low/sendmail/', views.sendmail),
    path('adminlogin.html/adminlog/manage/low/return/', views.returned),
    path('adminlogin.html/adminlog/detail/', views.fetch),
    path('adminlogin.html/adminlog/detail/fetchnext/', views.fetchnext),
    path('adminlogin.html/adminlog/detail2/', views.fetchnext2),
    path('adminlogin.html/adminlog/detail3/', views.fetchnext3),
    path('logged/track/', views.check1),
    path('logged/try/', views.tr),
    path('ss/tryg/', views.trg),
    path('adminlogin.html/adminlog/trya/', views.tra),
    path('logged/track/up/', views.up),
    path('logged/manage/', views.mm),
    path('logged/upload/', views.model_form_upload),
    path('logged/manage/returnall/', views.returnall),
    path('logged/manage/mmm/', views.mmm),
    path('logged/trackdetailss/', views.senddata),
    path('logged/All/', views.all),
    path('logged/track/next/', views.bulk),
    path('logged/track/updatetracker/', views.table),
    path('logged/track/updatetracker/update/', views.updatetable),
    path('logged/track/updatetracker/delete/', views.deletetable),
    path('logged/track/del/', views.dele),
    path('logged/track/done/', views.done),
    path('adminlogin.html/adminlog/manage/newadd/low/return/', views.returned),
    path('ss/nn/', views.teamain),
    path('/', views.xx)

]
