# Generated by Django 3.0 on 2019-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Address',
            field=models.CharField(default='dd', max_length=10, null=True),
        ),
    ]
