# Generated by Django 3.0 on 2019-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_customuser_select_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='division',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='LEADER', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.IntegerField(default=1234),
        ),
    ]
