# Generated by Django 3.0 on 2019-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20191211_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='select_dept',
            new_name='dept1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='division',
            new_name='div1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='contact',
            new_name='no1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='role',
            new_name='role1',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='pro_name',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='users',
            name='name1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
