# Generated by Django 3.0 on 2019-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20191211_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email2',
            field=models.EmailField(default=False, max_length=50),
        ),
    ]
