# Generated by Django 3.0 on 2019-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_users_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='no2',
            field=models.IntegerField(default=1234),
        ),
    ]
