# Generated by Django 3.0 on 2019-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_users_no2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=30, null=True)),
                ('Ttopic', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
