# Generated by Django 3.0 on 2019-12-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='teacher1',
            field=models.CharField(default='yasir', max_length=30),
        ),
    ]
