# Generated by Django 3.0 on 2019-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_users_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gname', models.CharField(default='no', max_length=80, null=True)),
                ('Gcount', models.IntegerField(default=0)),
            ],
        ),
    ]
