# Generated by Django 3.0 on 2019-12-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20191213_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(default='k', max_length=80),
        ),
    ]
