# Generated by Django 3.0 on 2019-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20191214_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='count',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
