# Generated by Django 3.0 on 2019-12-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20191214_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='yasir', max_length=30)),
                ('add', models.CharField(default='yasir', max_length=30)),
                ('no', models.IntegerField(default=0)),
            ],
        ),
    ]
