# Generated by Django 3.0 on 2019-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20191215_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='teacher',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='title',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
