# Generated by Django 3.0 on 2019-12-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20191221_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='addres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(default=True, max_length=20)),
                ('nor', models.IntegerField(default=True)),
            ],
        ),
    ]
