# Generated by Django 3.0 on 2019-12-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='qua',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='res',
            field=models.CharField(default='yasir', max_length=30),
        ),
    ]
