# Generated by Django 3.0 on 2019-12-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='gname',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
