# Generated by Django 3.0 on 2020-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_document_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, choices=[('synopsis', 'SYNOPSIS'), ('ppt', 'PPT'), ('report', 'REPORT')], max_length=255),
        ),
    ]
