# Generated by Django 3.0 on 2020-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_auto_20200106_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='aca',
            field=models.CharField(choices=[('18', '2018-19'), ('19', '2019-20'), ('20', '2020-21'), ('21', '2021-22'), ('22', '2022-23'), ('23', '2023-24'), ('24', '2024-25')], default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='domains',
            field=models.CharField(choices=[('BLK', 'BLOCKCHAIN'), ('WEB', 'WEBSITE'), ('DB', 'DATABASE'), ('SC', 'NETWORKS-SECURITY'), ('AI', 'ARTIFICIAL-INTELLIGENTS'), ('DM', 'DATA-MINING')], default=True, max_length=100),
        ),
    ]
