# Generated by Django 3.0 on 2020-01-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20200107_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='domainID',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
