# Generated by Django 3.0 on 2020-01-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_users_domainid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='teacher1',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='title1',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
    ]
