# Generated by Django 3.0 on 2020-01-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20200107_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Mobile_Number',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='title1',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
